### ISSUE TITLE
Should listeners match the API or exclude unused parameters?

### ISSUE THREAD

**Issue by jbphet** [phetsims/phet-info#110]
During the Gas Properties code review (see https://github.com/phetsims/gas-properties/issues/111), I flagged several functions defined in `link` statements for having unused parameters.  For example,

```js
      // When the stopwatch visibility changes, stop it and reset its value.
      this.visibleProperty.link( visible => {
        this.isRunningProperty.value = false;
        this.timeProperty.value = 0;
      } );
```

In response, @pixelzoom said over Slack:

> My understanding is that, in general, function signatures should match the API, including params that are unused.   I don’t see this mentioned in any checklist, but I do recall discussing it in the context of scenery input listeners.
> 
> On the other hand, the param for `link` is `function(newValue,oldValue)`, and we regularly omit `oldValue`.

I have been omitting unused function parameters in cases such as these, partly because they get flagged by IntelliJ, but more importantly because I think it make the code easier to read.  It would probably be good to clarify our coding standard on this.

**Comment by pixelzoom** [comment]
9/25/19 discussion about this on Slack with @jbphet:

Chris Malley 11:11 AM
In the not-too-distant past, you advocated not including unused parameters in callbacks.  How do you feel about this case?
```js
      Property.multilink(
        [ styleProperty, activeProperty, colorProperty ],
        ( style, active ) => {
          // some algorithm that uses style and active 
        } );
```

John Blanco:office: 11:13 AM
To me, that code is perfectly clear - it is triggered by changes to the three properties in the list but doesn't need the third on in the handler.  So yes, I'd prefer that over including an unused 'color' parameter.

Chris Malley 11:14 AM
How about this?

```js
      Property.multilink(
        [ property1, property2, property3, property4 ],
        ( value1, value2, value3 ) => {
          // some algorithm that uses value1 and value3, but not value2 or value4
        } );
```

John Blanco:office: 11:15 AM
I think I'd rearrange the order so that the used parameters were first.

Chris Malley 11:17 AM
For these “array of dependency” type observers, I think I disagree.  After encountering this “omit the params that you don’t use approach” (throughout Vector Addition), I have a strong preference for an accurate callback signature, and not having to fiddle with order.

John Blanco:office: 11:19 AM
Would you advocate for matching callback signatures in all cases based on this?
BTW, part of the reason that I like omitting the unused params is that my IDE flags it as a problem, and I find this helpful in many situations, so I'd rather not simply turn it off.  Does yours?

Chris Malley 11:21 AM
Not sure about all cases.   But this pattern is proving to be generally easier to maintain:
```js
      Property.multilink(
        [ property1, property2, ..., propertyN ],
        ( value1, value2, ..., valueN ) => {
          ...
        } );
```
… regardless of what’s inside the `{...}`

John Blanco:office: 11:24 AM
Understood.  I'm not super attached to either approach, or something hybrid, so we can discuss at dev meeting or in a GitHub issue.  Maybe there would be a way to flag unused params in constructor and method definitions, but not in anonymous callbacks.

Chris Malley 11:25 AM
By “flag”, do you mean the “Unused parameter” highlighting in WebStorm’s editor?  I don’t mind that at all. For these specific cases, it shows me that there is a Property that triggers an update, but whose value is not relevant to the update algorithm.

John Blanco:office: 11:37 AM
Yes, that's what I mean by "flag".

**Comment by zepumph** [comment]
I think that I am with @jbphet on this. Because @pixelzoom's argument in for the first snippet:

```js
      // When the stopwatch visibility changes, stop it and reset its value.
      this.visibleProperty.link( visible => {
        this.isRunningProperty.value = false;
        this.timeProperty.value = 0;
      } );
```

Is incomplete, because there are two other params that you aren't adding after the "value" arg. From Property._notifyListeners:

       this.changedEmitter.emit( this.get(), oldValue, this );


 Furthermore if we decide to add a fourth do we then have to go to all `link` calls and add an unused 4th param?

**Comment by pixelzoom** [comment]
10/3/19 dev meeting:

I reiterated what I said above about WebStorm flagging unused params:
> it shows me that there is a Property that triggers an update, but whose value is not relevant to the update algorithm.

Consensus was to leave up to developer discretion.

**Comment by pixelzoom** [comment]
Here's what was added to the CRC:

- [ ] Putting unused parameters in callbacks is up to developer discretion, as long they are correct wrt to the actual callback signature.

For example, both of these are acceptable:

```js
Property.multilink(
  [ styleProperty, activeProperty, colorProperty ],
  ( style, active, color ) => {
    // some algorithm that uses style and active 
} );

Property.multilink(
  [ styleProperty, activeProperty, colorProperty ],
  ( style, active ) => {
    // some algorithm that uses style and active 
} );
```

This is not acceptable, because the 3rd parameter is incorrect.

```js
Property.multilink(
  [ styleProperty, activeProperty, colorProperty ],
  ( style, active, lineWidth ) => {
    // some algorithm that uses style and active 
} );
```
