### ISSUE TITLE
remove comprehensive performance test from code-review checklist

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#111]
From the code-review checklist:
> - [ ] Does the sim perform as desired across the range of supported platforms? (eg, not too slow on slow platforms, not too fast on fast platforms)

Imo, this should be revised or removed from the checklist.  As a reviewer, I don't have the time or resources to be able to test "across the range of supported platforms".   In general, this should be done well before code-review, and documented in a GitHub issue. 

Assigning to @ariel-phet to prioritize and assign.

**Comment by ariel-phet** [comment]
@pixelzoom feel free to remove, I think this is a bit vestigial from when we had some issues with "clock speed" of the sim with things like Energy Skate Park (it varied greatly in seeming speed of the model).

However, with the thorough QA processes we have in place these days, I agree this item is no longer relevant since QA will evaluate such issues in the dev testing cycle. 

Feel free to remove at your convenience.

**Comment by pixelzoom** [comment]
@ariel-phet FYI, I change the above checklist item to this:

> - [ ] Is there a GitHub issue documenting a comprehensive performance review on all supported platforms?

Closing.
