### ISSUE TITLE
Potentially streamlining CRC and moving multiple items to new "conventions" doc

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/phet-info#119]
We have gone back and forth on this question a bit in the past, moving items into the CRC and then the CRC getting quite long.

@pixelzoom had brought up the possibility of moving multiple items to a sub-document that captures coding conventions that most people know after being at the project awhile, but could still be used for reference.

We should discuss if we want to take this step and what types of items belong.

**Comment by pixelzoom** [comment]
I don't find the current length of the CRC to be a problem.  But that's because I've done a lot of PhET code reviews, I helped write the CRC, and I'm very familiar with related topics like PhET coding conventions. So I don't have to read every item in the checklist, and can pretty much blaze through it.  For a "self" code review, I can get through the entire checklist in < 1 hour.  When reviewing someone else's code, it takes me longer, but most of that time is spent understanding and reviewing the sim, not reading the checklist.

On the other hand, if you're not familiar with the CRC (or related info, like PhET coding conventions), and haven't done many PhET code reviews, it's going to take a long time to complete the CRC.  And it's going to take a long time regardless of where the info is located.  And the way to get faster/better is to do more code reviews (perhaps riding along with someone), so you get more familiar with everything involved in a code review.

So my feeling is that the CRC is good "as is" for now.

**Comment by chrisklus** [comment]
@pixelzoom is going to do a first pass and add annotations to indicate which items do not need as much attention.

**Comment by pixelzoom** [comment]
Summary of what I did:

* Add a new "GitHub Issues" section at the very beginning of the CRC.  This is a list of GitHub issue that every sim should have, documenting tasks that the developer should have completed. If this hasn't been done, the instructions say:

> If any of these issues is missing, or have not been completed, pause code review until the issues have been created and addressed by the responsible dev.

* For the "Coding Conventions", "Documentation", and "Type Expressions" sections, I added a paragraph like this at the beginning of the section:

> This section deals with PhET coding conventions. You do not need to exhaustively check every item in this section, nor do you necessarily need to check these items one at a time. The goal is to determine whether the code generally meets PhET standards.

* For "Accessibility" and "PhET-iO" sections, I added a sentence like this:

> This section may be omitted if the sim has not been instrumented for a11y.

Back to @ariel-phet to determine if this is sufficient.

**Comment by ariel-phet** [comment]
@pixelzoom yes I think that is sufficient for the moment. The CRC has been an evolution, the next step is probably to have more spreading of the love for such reviews :).
