### ISSUE TITLE
Error on create-sim

### ISSUE THREAD

**Issue by bardobrado** [phetsims/phet-info#129]
I followed all instructions but i'm unable to create a new sim.

This is the error that i'm getting:

`atal error: Perennial task failed:
Error: grunt unpublished-README in ../MMGD failed with exit code 3 and stdout:
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'lodash'
Warning: Task "unpublished-README" not found. Use --force to continue.

Aborted due to warnings.

  at ChildProcess.process.on.code (/home/rahto/Documents/phet/phetsims/perennial/js/common/execute.js:72:17)
  at emitTwo (events.js:126:13)
  at ChildProcess.emit (events.js:214:7)
  at maybeClose (internal/child_process.js:925:16)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

Full Error details:
{
  "cmd": "grunt",
  "args": [
    "unpublished-README"
  ],
  "cwd": "../MMGD",
  "stdout": "Loading \"Gruntfile.js\" tasks...ERROR\n>> Error: Cannot find module 'lodash'\nWarning: Task \"unpublished-README\" not found.\u0007 Use --force to continue.\n\nAborted due to warnings.\n",
  "stderr": "",
  "code": 3
}
`

**Comment by Piet-G** [comment]
This error is still present, I'm on windows btw.

**Comment by NickCrews** [comment]
Hey @pixelzoom or @samreid, apparently you're the top maintainers for this repo, do you have notifications set up for when someone opens an issue here? I'm sure you have tons on your plate, but I see several issues here (including me, that's why I'm here :) ) from someone outside PHET, that look like they've been totally missed by anyone at PHET.

**Comment by pixelzoom** [comment]
I @NickCrews. Thanks for the poke :)  Unfortunately, PhET currently doesn't have a convention monitoring issues. I tend to work off of mentions (which is why I received your comment above), while other developers may not see and issue until it's assigned to them.  

Assigning to @ariel-phet to prioritize and assign this issue.  And perhaps to address the issue of how developers should monitor public repositories that are used by the GutHub community.

**Comment by zepumph** [comment]
@NickCrews, thanks for the ping! The documentation was updated over in https://github.com/phetsims/phet-info/pull/148. @bardobrado @Piet-G @NickCrews let us know if this issue continues.
