### ISSUE TITLE
Are github label scripts still needed?

### ISSUE THREAD

**Issue by mattpen** [phetsims/phet-info#165]
https://github.com/organizations/phetsims/settings/repository-defaults

It looks like we can set the default labels for all new repos in the phetsims organization through a settings page now.  Should we do this instead of maintaining the label scripts?

**Comment by mattpen** [comment]
> Adding, editing, or deleting a default label does not add, edit, or delete the label from existing repositories.

It seems like this doesn't completely replace all the scripts that we use, but it could be used to replace [the script that adds all labels to a new repo](https://github.com/phetsims/phet-info/blob/master/github-labels/new-repo-add-labels.sh), and probably could be used in place of [the data file that holds our labels](https://github.com/phetsims/phet-info/blob/master/github-labels/github-labels).

I tagged for dev meeting to determine priorities and timeline.

**Comment by jessegreenberg** [comment]
Discussed during developer meeting on 8/19/21 - 

@mattpen mentioned that some people have had trouble using the scripts so it might be beneficial to move to something that github directly provides.

Since we cannot replace all of our scripts or labels yet, we agreed that it doesn't make sense to replace some but keep others and have two different mechanisms for setting/modifying github labels.

Closing this issue for now.
