### ISSUE TITLE
Should class attributes typically be initialized at the declaration site, or typically in the constructor?

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-info#190]
At today's TypeScript meeting, we asked the question: Should class attributes typically be initialized at the declaration site, or typically in the constructor?

The conventions doc currently reads:
> Class properties can be initialized either where they are declared, or in the constructor. It is up to developer discretion, but please try to be consistent, and adhere to the spirit of existing code.

But now that we have had a chance to take it for a test drive, many developers on the team prefer initializing things at the declaration site.  We were thinking of a new convention like:

> Where possible, it is preferable to initialize class attributes at their declaration site.  

However, we didn't want to adopt this as a new formal recommendation without discussing with @pixelzoom first.

Tagging for an upcoming meeting, or @pixelzoom you can comment asynchronously if you prefer.

**Comment by pixelzoom** [comment]
I prefer the current convetion - at developer discretion.  

Because of PhET-iO (and the need to create tandems) there are many things that can only be initialized in the constructor. I'm not a fan of initializing some things at declaration, and other things in the constructor.  Even less a fan of having to move initialization from declaration to constructor, like when I find out I need to add PhET-iO instrumentation to something.

**Comment by chrisklus** [comment]
From 5/9 supplemental TypeScript meeting:

We are on board with developer preference, with preference to consistency within a class. This is noted here: https://github.com/phetsims/phet-info/blob/master/doc/typescript-conventions.md#initialization-of-class-properties. Closing.
