### ISSUE TITLE
Broken link in phet-software-design-patterns.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#195]
In https://github.com/phetsims/phet-info/blob/master/doc/phet-software-design-patterns.md

```
In [Molecule.js](https://github.com/phetsims/molecules-and-light/blob/master/js/photon-absorption/model/Molecule.js),
```

This file no longer exists.

**Comment by jessegreenberg** [comment]
Thanks, it would probably be best if it points to a specific SHA. In this case it been broken since we moved molecules-and-light code into greenhouse-effect. I updated the link and referenced line numbers in the doc to match https://github.com/phetsims/greenhouse-effect/blob/c3902b1c402cd2ca699a68938c98c7b2387844dd/js/micro/model/Molecule.js.
