### ISSUE TITLE
visibleProperties in model or in view?

### ISSUE THREAD

**Issue by marlitas** [phetsims/phet-info#197]
In the code review for Mean Share and Balance, @pixelzoom made a recommendation to move visible/isShowingProperties from the model to the view: https://github.com/phetsims/mean-share-and-balance/issues/72

An example of visible/isShowingProperties from Mean: Share and Balance.
```js
this.predictMeanVisibleProperty = new BooleanProperty( false, {
      tandem: options.tandem.createTandem( 'predictMeanVisibleProperty' )
    } );
this.meanVisibleProperty = new BooleanProperty( false, {
      tandem: options.tandem.createTandem( 'meanVisibleProperty' )
    } );
this.tickMarksVisibleProperty = new BooleanProperty( false, {
      tandem: options.tandem.createTandem( 'tickMarksVisibleProperty' )
    } );
```

In talking through this with @samreid we discovered that this is not consistent across all published PhET-iO sims. 

In the PhET-iO published sim Gravity and Orbits, visible/isShowingProperties are housed in the model.
```js
this.showGravityForceProperty = new BooleanProperty( false, { tandem: tandem.createTandem( 'showGravityForceProperty' ) } );
this.showVelocityProperty = new BooleanProperty( false, { tandem: tandem.createTandem( 'showVelocityProperty' ) } );
this.showPathProperty = new BooleanProperty( false, { tandem: tandem.createTandem( 'showPathProperty' ) } );
this.showGridProperty = new BooleanProperty( false, { tandem: tandem.createTandem( 'showGridProperty' ) } );
```

The first question this brought up addresses developer opinion on whether visibleProperties belong in the model or view based on MVC principles as well as PhET patterns and conventions. We believe this is a larger dev team discussion to ensure consistency across sims. If we consider the model to be only the physical/mathematical/biological representation, then those view properties do not belong in the model. If we consider the model in a software engineering MVC sense, then they probably do belong in the model.

The second question is based on PhET-iO client/designer preference. What is the best user experience for finding visible properties?

**Comment by pixelzoom** [comment]
> We believe this is a larger dev team discussion to ensure consistency across sims.

Just a note that it's been up to developer discretion in the past. Unfortunately, PhET-iO exposes where the Properties "live", so it may be useful to have a convention.

>  If we consider the model in a software engineering MVC sense, then they probably do belong in the model.

Not sure I agree with this. There is not necessarily a sngle "model" in applications that use MVC, and that's certainly the case for PhET sims.  For example, sun buttons use the MVC pattern and have a model, which is irrelevant to the top-level sim model.

**Comment by marlitas** [comment]
>  There is not necessarily a single "model" in applications that use MVC, and that's certainly the case for PhET sims. For example, sun buttons use the MVC pattern and have a model, which is irrelevant to the top-level sim model.

I don't think we are arguing that there is a singular model, but rather that any data or logic based properties belong in a model (top-level or not) instead of the view with a strict software engineering MCV interpretation. The fact that sun buttons have their own model seems to align exactly with my experience of MVC patterns.

I think there is an argument to be made though that although we attempt to strictly use the MVC pattern, the lines do often get blurred since we do not have controllers. This can sometimes bring logic into the view which would normally not be there.

**Comment by zepumph** [comment]
It is worth noting that there is precedent for both. Noting `GQViewProperties`. 

@jonathanolson: I like keeping state in the model, so visibleProperties go there so that all serialization/resetting is in the model.

@zepumph: I don't see this as a very large problem, because in almost all cases, there will be linked elements ensuring that these are clearly defined where they are used (in the view buttons/etc).
For example: graphingQuadratics.exploreScreen.view.quadraticTermsAccordionBox.linearTermCheckbox.property links to graphingQuadratics.exploreScreen.view.viewProperties.linearTermVisibleProperty. It could just as easily link back to the model.

We then went into a pretty large conversation about how PhET's MVC architecture is not conforming to tradition web application MVC. All Properties don't exist in the "model" at PhET. PhET's model (we called it a "domain" model), exists often as the content of the simulation. In the view container, we have many subset MVC patterns built into the view. Node holds its own state (model). ButtonModel is split out of ButtonNode, but PhET-iO combines them back (mostly because all other components integrate the model (slider/combobox/accordionbox).

@jonathanolson: "model/view" separation sounds like a dichotomy, but in actually it is more blended because there are mini MVCs all over the place.

We should ask the PhET-iO designer to determine how to proceed. Most likely, design team as a whole to discuss this at a PhET-iO meeting to all determine if we should tighten up this pattern into a convention (from dev discretion). Reminder here that linked elements may make this moot. 

Thanks @marlitas!

**Comment by jonathanolson** [comment]
This came up today, where I had put string Properties under the "general.model" tandem, it was requested to move it to "general.view", and then there's some confusion and disputes about where it should go.

**Comment by samreid** [comment]
Today @arouinfar and @kathy-phet commented that this decision should be up to developers.  From a design standpoint, either is OK (with the help of Linked Elements).  So perhaps it should go to dev meeting?

**Comment by zepumph** [comment]
Saving this for next time.

**Comment by samreid** [comment]
> Today @arouinfar and @kathy-phet commented that this decision should be up to developers. From a design standpoint, either is OK (with the help of Linked Elements). So perhaps it should go to dev meeting?

I was somewhat surprised to hear this, since @zepumph and I previously concluded that linked elements cannot process API commands.  So it is not a trivial "either is OK" matter for which is a linked element vs core element.  Only core elements can process API commands.  If we revisit this, and make it possible for LinkedElements to process commands, then I can see it mattering a lot less whether things are linked or not.

**Comment by marlitas** [comment]
While navigating through studio to test the nested structure of checkboxes in Mean: Share and Balance, I was momentarily confused by the visibleProperties being in the view. 

- I accidentally navigated to those properties first thinking they were actually the checkboxes, then realized my mistake.
- Was further confused when those properties are nowhere near the checkboxes they are related to in the studio tree (I know this is somewhat in part to the way studio tree elements are sorted alphabetically). 

Perhaps my perspective does not align with that of a PhET-iO studio user, but this series of events made my user experience of studio in this moment clunky and confusing. As a user coming in I would expect that something in the view that contains `predictMean` would provide me information and control over the check-box element with the label "predict mean". This is not the case.

This becomes even more baffling when I find out I can change the value of that property both in the `predictMeanVisibleProperty` as well as through the `predictMeanCheckbox` linked property, even though they appear to be two distinct elements in the view according to the studio tree.

I discussed this with @samreid and we had a fruitful conversation about MVC at PhET and the blurry line between convention and developer preference. We are not sure if this issue can be left up to developer preference because of the way it affects PhET-iO user experience.

At this point I am still not convinced that visibleProperties belong in the view... I will be moving Mean: Share and Balance visibleProperties back to the model until a future decision indicates I should do otherwise.

**Comment by kathy-phet** [comment]
Hi all, 
@arouinfar and I have long dealt with the properties being split between view and model, so that explains our comments ... we are used to it and the Linked elements resolved the painpoints for us / the instructional designer. 

I would say for uniformity, it would be nice if they were all in the MODEL because that feels like the place where they can all be collected. I know there are properties that would not make sense to move to the view, at least that is what I have deduced from multiple conversations. 

If developers can agree on the model, that would be nice, but the Linked Elements reduces the issue for Amy and I, because it is discoverable no matter where it is. 

And regarding Sam's comment above, I believe @arouinfar and I have see Linked Elements that link to properties in the view and some that link to properties in the model. Regardless, you will need linked properties to make it discoverable, so I don't think this choice is really alleviating the issue that you mentioned, Sam. The properties do not live within the checkbox within Studio so are linked. 

As long as we have a uniform message to clients that the linked elements do not support API calls, I think they are the best solution at the moment. I don't want to open up the option to do API calls to these intermediary linked names ... it seems way to complex to me to support using either name, imo. 

K

**Comment by pixelzoom** [comment]
There are very fundamental misunderstanding about MVC at play in this discussion. And I'm dismayed that we are still speaking of "THE model", and making decisions that are actually contrary to MVC.  I have very specifiic (and I feel, well-informed) reasons for where I've located Properties.  But tell me where you'd like the Properties in the sims that I'm responsible for, and I'll relocated them.

**Comment by kathy-phet** [comment]
@pixelzoom - note the caveate of - if the developers agree they can go in one spot. I'm not suggesting to declare it has to be one spot. With the Linked elements, the instructional designers can find what we need, and it works.

**Comment by samreid** [comment]
> There are very fundamental misunderstandings about MVC at play in this discussion.

https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller says

* Model - The central component of the pattern. It is the application's dynamic data structure, independent of the user interface. It directly manages the data, logic and rules of the application.
* View - Any representation of information such as a chart, diagram or table. Multiple views of the same information are possible, such as a bar chart for management and a tabular view for accountants.

For example, in Geometric Optics, `virtualImageVisibleProperty` is *data* that models whether the user is interested in the virtual image or not. This model data is representation-independent. There may be many views that need to know whether the user is interested in the virtual image so that they may present their information accordingly. `virtualImageVisibleProperty` is not itself "a representation of information" (in the Wikipedia terminology above)--it is part of the underlying model data.

> Unfortunately, PhET-iO exposes where the Properties "live", so it may be useful to have a convention.

Linked elements help mitigate the difference in studio for designers, but the inconsistency will show in the API like so:

```
// Geometric Optics
geometricOptics.lensScreen.view.visibleProperties.virtualImageVisibleProperty setValue [true]

// Gravity and Orbits
gravityAndOrbits.modelScreen.model.showVelocityProperty setValue [true]
```

**Comment by pixelzoom** [comment]
Quoting a Wikipedia article that makes it sound like an application has "a" (singular) dynamic data structure (aka model) doesn't make it right.

If I have an `expandedProperty` for an AccordionBox, you seem to be OK with it living right alongside something like `particleVelocityProperty` in the domain model. (Note that I said "the domain model", not "THE model.").   Imo that pollutes the domain model and is anti-MVC.

But supposing that we go the route of putting all Properties like `expandedProperty` in "the model"... How do you propose to move AccordionBox's default `expandedProperty` into "the model"?

**Comment by pixelzoom** [comment]
First we need discuss whether MVC an be applied in multiple places in an application, or whether we must have one appliction of MVC, with one model, etc.    If we can get past that, then...

Perhaps we should discuss whether there's value in keeping the domain model separate from other "models" in an application. I think there's a lot of value in keeping them separate, which is the pattern that I've been using.  If PhET-iO adds yet-another limitation where that's not desirable, then so be it.  But I don't agree that good MVC design mean putting everything that can possibly be observed into a single "model".

**Comment by samreid** [comment]
> First we should discuss whether we agree that MVC an be applied in multiple places in an application, or whether we must have one appliction of MVC, with one model, etc. If we can get past that, then...

As has been said in both https://github.com/phetsims/phet-info/issues/197#issuecomment-1205388963 and https://github.com/phetsims/phet-info/issues/197#issuecomment-1205698423, a sim may have multiple mini-models and multiple views.  @jonathanolson said ""model/view" separation sounds like a dichotomy, but in actually it is more blended because there are mini MVCs all over the place". I don't see any argumentation in this issue that we must have one application of MVC with one model, etc.  It makes sense for each Node to create its own `visibleProperty` or `inputEnabledProperty` where appropriate.  Or for an accordion box to create its own `isExpandedProperty`. We do not say `measuringTapeNode.model.visibleProperty`, it is clearer and acceptable to say `measuringTapeNode.visibleProperty`.  Those mini-models are appropriate because they are created by the Node, specific to one Node, and do not contain sim-specific terminology.

However, for PhET-iO, we do form a central top-level distinction for model and view, and we do use those terms once per screen. Something sim-specific, such as whether the user is interested in seeing virtual images or not, should be defined in the sim model--note I did not say domain model--which does not need to be intermingled with the domain model.  

The constructor for Screen is:

```ts
public constructor( createModel: () => M, createView: CreateView<M, V>, providedOptions: ScreenOptions ) {
```

The constructor is not:

```ts
public constructor( createDomainModel: () => DM, createView: CreateView<DM, V>, providedOptions: ScreenOptions ) {
```

> Perhaps we should discuss whether there's value in keeping the domain model separate from other "models" in an application. I think there's a lot of value in keeping them separate, which is the pattern that I've been using.

In Circuit Construction Kit, CircuitConstructionKitModel has, among other things (organized and commented for clarity):

```ts
  public readonly showLabelsProperty: BooleanProperty;
  public readonly showValuesProperty: BooleanProperty;
  public readonly selectedZoomProperty: RangedProperty;
  public readonly currentZoomProperty: NumberProperty;
  public readonly isPlayingProperty: BooleanProperty;

  public readonly circuit: Circuit; // <-- this is the domain model
```

If there are only a few user settings, or a very simple domain model, would we want to mix them?  Where do we draw the line?

Also, how do we weigh the benefits of consistency against the cost to determine and implement consistent patterns?

**Comment by pixelzoom** [comment]
Feel free to discuss this while I'm out.  I don't have any further input.  If you'd like Properties relocated in the Studio tree, please create a sim-specific issue.  Identify the Properties by their current tandem name, and their new (relocated) tandem name.

**Comment by samreid** [comment]
Nov 17 2022 Dev meeting:

@jbphet: I think of the model as all of the model things, in addition to the domain model.  I do include things like `isShowingVectors` in the model.  Then it is one place for all of the model settings.  Then in creating the view, the view can observe those parts of the model.
@pixelzoom: So how do you separate out the domain model from the view-y parts in that case?
@jbphet: I usually section them off in comments.
@pixelzoom: but how about in studio.

We looked at greenhouse model in studio.

@samreid: In CCK, the domain model is nested under model.circuit
@kathy-phet: In CCK it is nice to have model.resistor.isDisposableProperty in the model.  Maybe our decisions here should be sim-specific.
@pixelzoom : `geometricOptics.lensScreen.view.visibleProperties.*` works really well.
@kathy-phet: I agree, this is a nice way to structure it in this case.
@samreid: We could put model.visibleProperties in the model.
@pixelzoom: This is micro-engineering, spending way too much time on something that is irrelevant.  How did I publish 10 sims with this approach and it was approved this way, why should we waste time going back and changing it?  I don't really want to discuss it further. It doesn't seem a good use of time.  Doesn't seem to matter how it is structured, as long as it is structured somehow.  Like @kathy-phet said, it can be sim-specific.  In future sims, if these should be elsewhere, just let me know.
@marlitas: Is it confusing for phet-io users having these properties in different places?
@kathy-phet: Working with @arouinfar, seeing some things in the view and some in the model is OK.  Using the autoselect and linked properties really helps.  So maybe it is ok to have different places.  Linked elements are great

@samreid: How does this pertain to the question @marlitas asked in the top comment?  Is it developer preference to put these properties in the model or view, as long as there is structure?
@kathy-phet: If there are just a few view properties, they do not need substructure.  At 5+ then it needs a level of nesting.
@pixelzoom: I add those intermediate levels quite a bit, for grouping.  It seems to work well.
@jbphet when you create that level in the tandems, do you also reflect that in the code?
@pixelzoom: Not necessarily, you can just create structural tandems without further refactoring.  For the visibleProperties, I did pull those out into one class and it made reset nice.

@pixelzoom: I cannot wait for structure design from the phet-io team, I have to anticipate it or the overall design will take too long.  I feel it is working effectively now, without having to get the designers to say how to structure everything.

Summary:
8 votes for "developer preference as long as there is sufficient structure" - where structure means nesting and not parallel subtrees in model and view.
1 abstain

**Comment by samreid** [comment]
The visibleProperties are now used in Core Description, and having them defined in the view is a significant hassle. It is not just an aesthetic preference, and it is not a micro-engineering concern. In https://github.com/phetsims/number-pairs/issues/206#issuecomment-3423521675 I wrote:

> This is a great example for why `Property` instances for view visibility should be instantiated in the model. If it was, we could easy access `doubleVisibleProperty` for usage in the `TenScreenSummary`. However, it is created in the view which does not exist at the time we wish to create the `TenScreenSummary`.

Instead I will have to use a workaround or rearchitect this part.

**Comment by pixelzoom** [comment]
> ... Instead I will have to use a workaround or rearchitect this part.

It's not absolutely necessary to specify the ScreenSummaryContent via options. And having Properties in the view is not the only situation where you might want to use something from the view in the ScreenSummaryContent.   In those cases, use ScreenView `setScreenSummaryContent` after the view components have been instantiated.  See for example ConcentrationScreenView.
