### ISSUE TITLE
Consolidate sim-deployment instructions and get rid of the build step

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-info#40]
@pixelzoom said:

> [1/6/17, 10:28:21 AM] Chris Malley: I'm having a difficult time navigating the deploy instructions since they were split up into N documents.

@jonathanolson said:

> [1/6/17, 10:33:10 AM] Jonathan Olson: I'm not sure how to correct instructions (I think they're generated now), I'll defer to others

**Comment by pixelzoom** [comment]
We should (unfortunately) discuss this at dev meeting, since some team members seemed to like the current arrangement.

**Comment by jonathanolson** [comment]
We could combine automated steps to help out also.

**Comment by zepumph** [comment]
Andrew and I made the current version of the sim deployment docs. I am sorry they aren't working out well, and I understand the problems with it. I am all for consolidation of the source files, as that is the reason that there is duplication, which makes it pretty hard to maintain. I will say that one of the main reasons that we decided to separate it was because the one huge file for all sim_deployments had gotten pretty unruly, and difficult to expect someone to read the entire thing fully when deploying (for example since that would involve reading phet-io and dev deploy items for a phet-production deploy). 

@samreid had at one point suggested one large source file (template), in which each line was marked with the types of builds it applied to, and then there was still a build step that separated out crisp instructions that only pertained to the build at hand (similar to what we have now). The main improvement here is that there is absolutely no repeat info, since all of the source is in one file. Maybe we should think about that sort of solution instead. That still involves the build step though.

Another strong consideration we have thought about is to keep whatever we do in markdown, because it works with github and our current environment so well.

**Comment by samreid** [comment]
I checked in a rough draft of deployment instructions here with the following features:
* All in one file
* No build step
* Emphasizes overall flow of the build for all types
* Shows steps for different types of build (phet/phet-io, dev/rc/prod) together so that the developer can understand how different builds relate

https://github.com/phetsims/phet-info/blob/master/deployment-info/combined.md

I created this as a rough draft for discussion, it is neither complete nor ready for use.  If we agree this style is desirable, the next step will be to make sure it covers all of the information clearly and concisely.

**Comment by zepumph** [comment]
That looks really nice, and isn't hard to read at all. Thanks for doing that @samreid.

**Comment by pixelzoom** [comment]
Looks much nicer than the make-based approach.  Have these instructions been tested?

**Comment by samreid** [comment]
> Have these instructions been tested?

No.  From https://github.com/phetsims/phet-info/issues/40#issuecomment-271774397

> I created this as a rough draft for discussion, it is neither complete nor ready for use.

**Comment by samreid** [comment]
@jonathanolson said it would be nice to color highlight the instructions, or at least bold the selectors.

**Comment by pixelzoom** [comment]
If/when we proceed with this... `grunt checkout-shas` is missing from the instructions.

**Comment by samreid** [comment]
@jessegreenberg says let's go for it!

**Comment by samreid** [comment]
After I flesh it out, I'll ask for a review.

**Comment by jonathanolson** [comment]
Would perennial's ```grunt checkout-shas --repo={{REPO}}``` be recommended (since it doesn't depend on what node_modules are in chipper)?

**Comment by zepumph** [comment]
Here is a first pass at a complete port from the make and build docs. What do people think?

**Comment by pixelzoom** [comment]
Looks great @zepumph, thanks for doing this.  I think this is superior to the `make` approach, both in usability and maintainability.  Unfortunately I don't have time to test drive it for accuracy, and probably won't until my next maintenance or production released.

I did notice that the title of this issue includes "get rid of the build step", and the instructions still contain "the build step" (Step 3).  Is the goal to make Step 3 unnecessary, to be done automatically by the deploy tasks? (e.g. `grunt deploy-production`)  I'm not convinced that we want to do that. Manually building (Step 3) and then testing (Step 4) seems like a good safeguard against deploying something that is broken.

@ariel-phet: When this is ready, highly recommended to have someone test drive all steps.

**Comment by zepumph** [comment]
I think instead we meant the building of the document itself (like we were doing with make whenever there was at change). Rather than the Sim.

**Comment by pixelzoom** [comment]
Ah, that makes sense. Thanks for the clarification.

**Comment by jessegreenberg** [comment]
Thanks @zepumph, looks great.  I just went through the steps for a maintenance release.   I just changed the wording for the maintenance release note under Step 1 so it is clear that this step is only necessary when dependency repos need to be branched.

**Comment by zepumph** [comment]
Thanks @jessegreenberg, I hope anyone feels free to edit and refine it. I'm going to close this issue, if there are more problems or discussions to have lets make new issues for them. There is still more to do, but I would rather not make this a super issue.
