### ISSUE TITLE
Update RC checklist template to include credits and screenshots 

### ISSUE THREAD

**Issue by zepumph** [phetsims/phet-info#50]
From dev meeting today. I will get @phet-steele to check on it.

**Comment by zepumph** [comment]
From the dev meeting again, I will remove the Legends of Learning checkbox as well.

**Comment by zepumph** [comment]
I stripped out the LOL task, and added the sceenshot/credit update steps for once the rc testing is done. Tagging @phet-steele so he can take a look at it. Please change inline or in issue if there are problems. Closing.

**Comment by phet-steele** [comment]
@zepumph I don't see a change in github

**Comment by zepumph** [comment]
Sorry, how about now?

**Comment by phet-steele** [comment]
I'm not generally a fan of this @zepumph.

- These boxes would often go ignored and unchecked when another RC is needed.
- Having them here does NOT capture the case of spot checks since spot checks do not use this template. Spot checks, though, are often when screenshots and credits are missed. Additionally, no, I don't think a separate template for spot checks would be helpful.
- It's not always the case that QA decides when all testing is done and the sim is ready for publication.

I don't think there is a good place for these two steps in the QA workflow. They already exist as steps in the sim deployment guide. Assuming developers are responsible enough to work through those steps every time to avoid deployment errors, the screenshot/credits steps serve as a decent catch-all regardless of the QA task. This seems much easier, and since it already exists why duplicate the steps?

**Comment by zepumph** [comment]
I agree, this does not seem to be the best solution, especially if we are trying to make it full proof. @ariel-phet could you please comment. I'm not familiar with full stack sim development enough to know what is best. @phet-steele's solution above sounds nice to me.

**Comment by zepumph** [comment]
@ariel-phet and @phet-steele talked about this before closing.
