### ISSUE TITLE
Shall we add an item to the code review that forbids setTimeout and setInterval?

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-info#59]
In https://github.com/phetsims/energy-skate-park-basics/issues/380#issuecomment-330740734 @jonathanolson said:

> Please don't use setTimeout, for the reasons it is banned from usage by our code review guidelines. 

Should we add entries to the code review checklist forbidding `setTimeout` and `setInterval`?

**Comment by samreid** [comment]
We could catch these even more eagerly if we forbid them with lint rules.

**Comment by pixelzoom** [comment]
I'd prefer a lint rule to yet-another checklist item.

**Comment by zepumph** [comment]
I wonder what is best here. I see many setTimeout calls in places that seem fine to me. In aqua, the sonification wrappers, yotta. We use the same lint rules to lint those repos as we do sim code. 

>Please don't use setTimeout, for the reasons it is banned from usage by our code review guidelines.

I wonder if @jonathanolson can speak to what these "reasons" are. I see tons of usages in joist, as well as implementations in some Timer types in common code.  I think it warrants discussion before a blanket lint rule is implemented that isn't helpful because it creates too many false negatives.

**Comment by jonathanolson** [comment]
> I wonder if @jonathanolson can speak to what these "reasons" are. I see tons of usages in joist, as well as implementations in some Timer types in common code. I think it warrants discussion before a blanket lint rule is implemented that isn't helpful because it creates too many false negatives.

The reasons are that if window.setTimeout or window.setInterval are used, then generally it means the sim can't accurately be used to play back event streams in an identical fashion, since it depends on external timing (the setTimeout/setInterval will potentially execute at a different time, particularly if it shouldn't have been executed at all, e.g. if a sim is paused).

In aqua/yotta (and potentially the sonification wrappers), it isn't in the sim, so it wouldn't affect playback.

**Comment by zepumph** [comment]
Makes sense thanks. I'm in favor of adding this item to the checklist, or somehow branching some eslint code into a Sim only and all lint rules.

**Comment by samreid** [comment]
If there aren't too many occurrences outside of sim code, those cases could use `// eslint-disable` directives.

**Comment by zepumph** [comment]
I think we should explore a lint rule.

**Comment by pixelzoom** [comment]
There is already an item in the CRC.  It was added by @samreid on 12/1/17.  The commit message does not indicate that it was added to address this issue.

> - [ ] All dynamics should be called from Sim.step(dt), do not use window.setTimeout or window.setInterval. This will help support Legends of Learning and PhET-iO.

Adding these to bad-text.js lint rule seems problematic, since we may use those tokens elsewhere.

**Comment by pixelzoom** [comment]
Having a code-review item seems to have been sufficient for the past 2 years, so I propose that we close this issue and take no further action on the lint rule.

**Comment by zepumph** [comment]
I agree, but also thought I'd mention that there is bad text for only sims if you want to investigate adding them there. 

I'm a proponent of more list rules and less checklist items. This is both for Devs that have been here for ages, but also in helping the onboarding process.

**Comment by pixelzoom** [comment]
I agree that lint rules are preferred in general.  I do not agree that they are always worth the cost in practice, or in this specific case.

**Comment by pixelzoom** [comment]
10/3/19 dev meeting:

@zepumph is going to check for these in bad-text.js:

`window.setTimeout`
`setTimeout`
`window. setInterval`
`setInterval`

**Comment by zepumph** [comment]
See also https://github.com/phetsims/chipper/issues/737 if a regex is easier (I don't think it will be).

**Comment by zepumph** [comment]
I added this lint rule today, and ended up finding a lot of places where this was used. Most of them were tests/joist code where I think they actually belonged, but there were a few usages that likely should be converted. I think this is best as a chip-away issue. Assigning responsible devs, and the last one can flip the rule back on (or assign to me and I can.

When converting, you can just escape it with `// eslint-disable-line bad-sim-text`, but these files were flagged by me here because I felt like they felt like usages that should be fixed (though please correct me if I'm wrong).

- [ ] @jbphet area-builder\js\game\model\QuizGameModel.js
- [ ] @jonathanolson build-a-molecule/js/view/CollectionBoxNode.js
- [ ] @samreid circuit-construction-kit-common/js/view/CapacitorCircuitElementNode.js
- [ ] @samreid circuit-construction-kit-black-box-study\js\blackbox\view\BlackBoxSceneView.js
- [ ] @jonathanolson scenery\js\display\WebGLBlock.js
- [ ] @jonathanolson scenery\js\util\Util.js
- [x] @zepumph phet-io\js\phetioEngine.js (see https://github.com/phetsims/phet-io/issues/1566)

**Comment by jbphet** [comment]
Fixed in Area Builder, checked above.  Unassigning myself.

**Comment by samreid** [comment]
I'm all set, thanks @zepumph.  Over to you @jonathanolson

**Comment by jonathanolson** [comment]
Apologies about the delay! Handled the above cases.

A few have come up, and I'm not confident in handling them myself:
```
/Users/jon/phet/git/john-travoltage/js/john-travoltage/view/vibrationController.js
  111:1  error  Line contains bad text: 'setTimeout('  bad-sim-text
  114:1  error  Line contains bad text: 'setTimeout('  bad-sim-text

/Users/jon/phet/git/scenery/js/accessibility/speaker/webSpeaker.js
  210:1  error  Line contains bad text: 'setTimeout('  bad-sim-text

/Users/jon/phet/git/tappi/js/view/SelfVoicingLandingDialog.js
  103:1  error  Line contains bad text: 'setTimeout('  bad-sim-text
```

@jessegreenberg are you familiar with these cases?

**Comment by jessegreenberg** [comment]
Thanks, these were easy to convert to stepTimer.  These were the last ones so I added what was commented out in bad-sim-text in https://github.com/phetsims/chipper/commit/56e25043d49b16ecbfa004b8d4216ec9f3c69e63. @samreid @zepumph is there anything else to do for this issue?

**Comment by zepumph** [comment]
Very exciting! Thanks
