### ISSUE TITLE
review chipper 2.0 "how to" doc

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#65]
In 1/4/18 dev meeting agenda, @ariel-phet requested discussion/review of 
https://github.com/phetsims/phet-info/blob/master/deployment-info/chipper-2.0.md

**Comment by pixelzoom** [comment]
My questions/comments …

> It's highly recommended that, where there is a brand: 'phet' in your build-local.json, it should be augmented by a brands: [ 'phet', 'phet-io' ]
> ...
> brand:phet for older chipper SHAs: to automatically build the phet brand instead of the adapted-from-phet brand.

I think we should get rid of ‘brand’ in build.json specification, no need to be backward compatible.  If you have an older chipper, use `--brand`.

> Most other build options should be preserved, and apply to all brands that are built.

Is ‘grunt —report-third-party’ handled automatically by production deploy?


> Chipper 2.0 also adds the `--debugHTML` option

Should this be on by default? Should there be a way to specify it in build-local.json?

> Normal dev deployments are assumed to be done from master 

I occasionally publish dev versions from a release branch. How do I do that? Is `--branch` supported for dev versions?

> To deploy a dev version, run: `grunt dev --brands={{BRANDS}}`
> ...
> `grunt rc --branch=1.7 --brands={{BRANDS}}`
> ...
> `grunt rc --brands={{BRANDS}} --branch={{BRANCH}}`
< ...
> `grunt production --brands={{BRANDS}} --branch={{BRANCH}}`

Is `--brands` optional? 


> **Helpful utilities***

This is an incomplete list, duplicates some of what's in `grunt --help`, contains some info that's not in `grunt --help`.   Recommended to get rid of this section and make `grunt --help` the source for info, and references for where to get more info.

> Deploying pre-chipper-2.0 things
 > See https://github.com/phetsims/phet-info/blob/master/deployment-info/sim_deployment.md

Should this doc be rolled into sim_deployment.md?  Or maybe have sim_deployment-1.md and sim_deployment-2.md (for chipper 1 and 2 respectively)?

**Comment by jonathanolson** [comment]
> I think we should get rid of ‘brand’ in build.json specification, no need to be backward compatible. If you have an older chipper, use --brand.

It would want to leave it in my build-local.json so I don't have to manually specify the brand when I check out older sim SHAs. That's why I left it in this document, as presumably it would still be useful to have.

> Is grunt —report-third-party handled automatically by production deploy?

Yes:
```js
// Update the third-party-licenses report
grunt.log.writeln( 'Running third-party report (do not ctrl-C it)' );
await execute( gruntCommand, [ 'report-third-party' ], '../chipper' );
await gitAdd( 'sherpa', 'third-party-licenses.md' );
try {
  await gitCommit( 'sherpa', `Updating third-party-licenses for deploy of ${repo} ${versionString}` );
  await gitPush( 'sherpa', 'master' );
}
catch ( e ) {
  grunt.log.writeln( 'Third party licenses are already up-to-date' );
}
```

> Should this be on by default? Should there be a way to specify it in build-local.json?

The debug HTML requires a second require.js step per brand (and is still uglified for phet-io), so it can cause a moderate slowdown. Normally I wouldn't use it, so I opted for default off. Let me know if you prefer otherwise.

> I occasionally publish dev versions from a release branch. How do I do that? Is --branch supported for dev versions?

That is not supported yet in chipper 2.0, as I'm not sure how it would work. Would it need to update master's package.json version also, or just on the branch? (If supported, I'd have an additional prompt to confirm with the user). I'm fine adding this, let me know.

> Is --brands optional?

No, people should be actively thinking about which brands should be deployed.

> This is an incomplete list, duplicates some of what's in grunt --help, contains some info that's not in grunt --help. Recommended to get rid of this section and make grunt --help the source for info, and references for where to get more info.

I can improve the documentation in perennial's docs.

**Comment by samreid** [comment]
> where there is a brand: 'phet' in your build-local.json, it should be augmented by a brands: [ 'phet', 'phet-io' ]

Preceding line is unclear

> chains# grunt dev --brands=phet,phet-io

Will the supported brands eventually be inferred from the package.json?

`faradays-law> grunt` works fine but
`perennial> grunt --repo=faradays-law` fails

We won’t really know how to update the instructions until we have tried them in practice.

**Comment by samreid** [comment]
@pixelzoom recommends clarifying the documentation that the debug HTMLs are automatically created for each production release.

**Comment by pixelzoom** [comment]
Clarify that `brands` in build-local.json is ignored for dev/rc/production deployment, it's only relevant to local builds.  In the case of deployment tasks, `--brands` is a required task argument.

**Comment by pixelzoom** [comment]
For build-local.json, indicate that `brand` is chipper 1.0, `brands` is chipper 2.0, and you may want to have both entries if you're using chipper 1.0 and 2.0.

**Comment by jbphet** [comment]
How is brand support handled for common libraries like sun that are buildable, and the components may be in an intermediate state where some support phet-io and some don't?

2nd paragraph - "Whenever this information is changed, perennial's grunt generate-data should be run, and the files
under perennial/data should be committed/pushed." - what happens if this is forgotten? -- This was discussed during dev meeting, and @jonathanolson said he would automate.

**Comment by jonathanolson** [comment]
Documentation improvements in https://github.com/phetsims/phet-info/commit/66b6e509a78584e1057f5aa755bb6b8b4099c8f2 (mis-tagged the issue, sorry).

> How is brand support handled for common libraries like sun that are buildable, and the components may be in an intermediate state where some support phet-io and/or accessibility and some don't?

Like any other sim. If the thing you can run (for the runnable) supports phet-io, then you can put it in the supportedBrands. Not every file in the repository needs to be implemented (or accessible).
