### ISSUE TITLE
missing GitHub labels in some repos

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#69]
I ran into this when attempting to add the "status:blocking" label to a graphing-slope-intercept issue.  That label was missing.  And it looks like missing labels is an issue for many repos.

There are currently 50 labels in github-labels.json. (This was not easy to determine, by the way. Why is github-labels.json a single line?!?)

Several of the sims that I'm responsible for are missing labels:

> equality-explorer 48
function-builder-basics 42
gas-properties 48
graphing-slope-intercept 48

@mattpen could you please run the "add labels" process for these sims?

Note that there are other repos that are missing labels (smithers has only 7!)  And I wonder why we're managing a separate list (phetsims-repos.json) instead of using perennial/data/active-repos (which could be converted to JSON, if you really need JSON). Feel free to investigate those issues if you choose.

**Comment by pixelzoom** [comment]
Tried to label an issue in equality-explorer with "status:blocked", and that label is missing.

@mattpen ping.

**Comment by mattpen** [comment]
@pixelzoom - The four repos mentioned above now have all 50 standard labels.  `status:blocked` and `status:blocking` are not in the set of standard labels, so they are still missing from equality explorer.  Should we add it to the set (which one - blocked or blocking)?  What color (hex code) should it be?

> Note that there are other repos that are missing labels (smithers has only 7!)

Developers should be running the add-labels.sh script when they create a new repo, otherwise they will be missing.  It is a line in the [checklist for a new sim](https://github.com/phetsims/phet-info/blob/master/checklists/sim_new_checklist.md) but I don't think we have a checklist for new repos in general.  It's a pretty trivial task so I'm happy to run the script if I'm assigned an issue with a request to do so.

> There are currently 50 labels in github-labels.json. (This was not easy to determine, by the way. Why is github-labels.json a single line?!?)

There was a bug when I was developing this script that was solved by eliminating the new lines in this file.  The process could certainly be improved by solving this bug (among others), but improving these scripts is not currently on my high priority list.

**Comment by mattpen** [comment]
> And I wonder why we're managing a separate list (phetsims-repos.json) instead of using perennial/data/active-repos

There are some repos that are "active" but are not in `active-repos`, primarily `website`.  I believe it was omitted because its large size is inconvenient for non-website-developers running clone-missing-repos.sh, but it's still needed in the github scripts.  The next time the scripts are updated we can switch to using active-repos, but we would still need a second list for exceptions.

> perennial/data/active-repos (which could be converted to JSON, if you really need JSON)

Plaintext is fine, but as stated above improving these scripts isn't high on my radar at the moment.

**Comment by pixelzoom** [comment]
@mattpen said:
> `status:blocked` and `status:blocking` are not in the set of standard labels, so they are still missing from equality explorer. Should we add it to the set (which one - blocked or blocking)? What color (hex code) should it be?

I think they are semantically 2 different labels.  But if they're not in the standard label set, let's just ignore them for now.  

> Developers should be running the add-labels.sh script when they create a new repo, otherwise they will be missing. It is a line in the checklist for a new sim but I don't think we have a checklist for new repos in general. It's a pretty trivial task so I'm happy to run the script if I'm assigned an issue with a request to do so.

Yep, I'm aware of it.  I thought we had decided to send requests to you.  But I'll go ahead and set things up so that I can run `add-labels.sh`. 

Re duplication in github-labels.json... Sounds like a significant amount of work to address, so I'm ok with punting for now.

I'll close this when I've successfully set things up to run `add-labels.sh`.

**Comment by pixelzoom** [comment]
Btw... GitHub credentials are stored in `~/.phet/.credentials`, and information about it is in a public README file?!? That's a security hole just waiting to be exploited.

**Comment by pixelzoom** [comment]
I went _way_ down the rathole on this one, spent > 1 hour trying to get `add-label.sh` working.  Imo, add-label.sh and the instructions are not ready for general use.  So unless someone wants me to spend more time on this, I will not be installing it now, and will continue to request that @mattpen handle updating github labels.
