### ISSUE TITLE
The Culling of the Labels, Part 1

### ISSUE THREAD

**Issue by phet-steele** [phetsims/phet-info#74]
I took some labels that have questionable usage and gathered some numbers. I did NOT check every label we have, and these are labels are just ones I'm guessing are not used often. There may be some labels that don't get used often that I didn't include because, in my head, they are used often enough 😄.

Total Uses are also given in a percentage of all issues in phetsims/ ever made.

| Label | Total Uses | Most Recent Use |
| --- | --- | --- |
| design:polish | 44 (0.25%) | 4/2/2018 |
| dev:chip-away | 21 (0.12%) | 3/31/2018 |
| dev:help-wanted  | 20 (0.11%) | 3/2/2018 |
| dev:model  | 31 (0.17%) | 3/18/2018 |
| project:requires-kathy | 36 (0.20%) | 3/6/2018 |

Compare this with labels used often, like:

| Label | Total Uses | Most Recent Use |
| --- | --- | --- |
| type:bug | 2282 (12.81%) | 4/6/2018 |
| design:general | 551 (3.09%) | 4/5/2018 |

I understand that sheer usage numbers may not correlate to usefulness, but maybe we should evaluate if PhET could still "function" without the ones in the first table. These are also surprisingly all used quite recently....I'd like lots of opinions from different people.

**Comment by phet-steele** [comment]
@ariel-phet if you'd like me to spend time getting numbers for ALL labels, let me know.

**Comment by zepumph** [comment]
Of the little utilized labels above, I find `chip-away` and `requires-kathy` to be valuable. I would also expect that there wouldn't be many issues that use those labels, as they are pretty specific imo. 

`dev:model` and `dev:help-wanted` seem more general, and their lack of usage could be related more to them being unhelpful. I personally never have used either (that I can currently remember).

**Comment by ariel-phet** [comment]
@phet-steele a few comments:

1. I think `dev:model` is an important label - it is denoting there is an issue or change to the model, not the design. The model is a very specific aspect of the sim, so this label has merit (and not surprising that we use it rarely since we prefer not to monkey with the model). But it has its place

2. I think `design:general` has quite a few uses because we have not parsed things more. This is where `design:usability` might be helpful

3. The `dev:chip-away` is a label we have definitely used, but we could potentially remove it. Basically those tend to be issues that we keep persistently on developer meeting so that they are getting addressed. It just helps give a quick reference...this is something we are chipping away at.

4. I think `dev:help-wanted` is vestigial from the original set that github provides. I think we very rarely use that one, and I would be fine culling it.

**Comment by ariel-phet** [comment]
Basically @phet-steele @amanda-phet others, I don't think "numbers" are necessarily going to tell the story. I am fine evaluating each label on its merit, and usage numbers may help clue us in to giving more scrutiny to certain labels. But it may just be easier to go through the various labels and put ones up for the chopping block.

**Comment by phet-steele** [comment]
Alright, doing all of our common labels (the ones in this repo). Hold on to your hats, this will be one big table.

**Comment by arouinfar** [comment]
A few thoughts...
* I find it very helpful to use labels to filter through issues assigned to me, even though I generally keep the number of issues assigned to me as small as possible.
* I agree with @ariel-phet's https://github.com/phetsims/phet-info/issues/74#issuecomment-379353222, especially points (2) and (5).
* `design:polish` is a newer label, so its raw use count may not tell the full story. I personally use this label quite a lot, and find it helpful to distinguish pixel polishing from heavier design issues.
* `design:general` is very heavily used because there aren't that many design labels. 
* I personally use all of the design labels, save for `design:phet-io`, and would be extremely disappointed to see any of them go.

**Comment by lmulhall-phet** [comment]
I think given the recent changes made to the labeling scheme we might want to close this issue... What are your thoughts @ariel-phet?

**Comment by ariel-phet** [comment]
Seems reasonable to close. Closing
