### ISSUE TITLE
delete-label.sh needs documentation in README

### ISSUE THREAD

**Issue by zepumph** [phetsims/phet-info#85]
From #84, I see commits from @jjohnson5253, can you add doc in the README?

**Comment by mattpen** [comment]
@zepumph - Can you review the doc updates when you get a chance?

**Comment by zepumph** [comment]
This is all very nice. Thank you.

Why do we need the list of repos in `github-labels/`, could the script just depend on perennial/data/active-repos instead?

Is there a difference between those two lists. Currently I see that there is a discrepancy (github labels has circuit-construction-ios-app)

**Comment by mattpen** [comment]
> Why do we need the list of repos in github-labels/, could the script just depend on perennial/data/active-repos instead?
> 
> Is there a difference between those two lists. Currently I see that there is a discrepancy (github labels has circuit-construction-ios-app)

We do need two lists, because there are active repos missing from "active-repos".  There are some repos, like `website`, which are active but very large and not collaborated on by all team members.  Because active-repos is shared by the clone-missing-repos script, this creates a significant inconvenience in terms of storage.

I've answered this question multiple times, so I'll add it to the doc.

**Comment by mattpen** [comment]
Docs updated, closing.
