### ISSUE TITLE
remove "Add an activity" from Master Checklist? 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#86]
In https://github.com/phetsims/equality-explorer-two-variables/issues/1#issuecomment-444278797, @amanda-phet said:

> (As an aside, I think we need to remove "add an activity" from this checklist. I have never once written a sim-based activity for a sim before publication. The primer draft is reasonable to make an issue about, but I have also not completed this before publication because I'm still catching up on primers for already-published sims.)

I believe that @ariel-phet is maintaining the Master Checklist, so assigning to him.

**Comment by amanda-phet** [comment]
@arouinfar thoughts on removing this checklist item?

**Comment by arouinfar** [comment]
@amanda-phet I've always interpreted that checklist item as: review legacy activities and move over the relevant, gold-starred activities (assuming activity terms have been accepted). I have never written an activity for a brand new sim.

I would recommend removing this item from [sim_new_cheklist.md](https://github.com/phetsims/phet-info/blob/master/checklists/sim_new_checklist.md). I think we should keep it in [sim_port_cheklist.md](https://github.com/phetsims/phet-info/blob/master/checklists/sim_port_checklist.md), but perhaps rephrase to something like, "Review gold-starred legacy activities". It might also make sense to move this item to the post-publication section, since we can't add activities to the sim page until the sim is live.

**Comment by amanda-phet** [comment]
@arouinfar thanks. That all sounds like what I was thinking, too.

**Comment by ariel-phet** [comment]
Changes made. Closing
